

export const SITE = {
  name: "CPD Academy",
  fullName: "Rwanda Health CPD eLearning Platform",
  shortName: "CPD Academy",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://healthcpds.com",
  defaultOgImage: "/og-image.jpg",
  twitterHandle: "@healthcpds",
  locale: "en_RW",
  phone: "+250 788 000 000",
  email: "info@healthcpds.com",
  address: "Kigali, Rwanda",
  founded: "2020",
} as const

export const DEFAULT_SEO = {
  title: "CPD Academy — Rwanda Health CPD eLearning Platform | Continuing Professional Development for Healthcare Professionals",
  description:
    "Accredited CPD courses for healthcare professionals in Rwanda and Africa. Earn verified certificates, track CPD hours, and advance your clinical career with expert-led courses in nursing, medicine, midwifery, pharmacy, and public health.",
  keywords: [
    // ============================================================
    // CORE CPD & ELEARNING KEYWORDS
    // ============================================================
    "CPD eLearning",
    "continuing professional development",
    "CPD courses for healthcare professionals",
    "online CPD for doctors",
    "CPD for nurses Rwanda",
    "CPD for midwives",
    "healthcare professional development",
    "medical CPD online",
    "clinical education platform",
    "CPD credits online",
    "accredited CPD courses",
    "verifiable CPD certificates",
    "CPD hours tracking",
    "continuing medical education",
    "CME online",
    "CME credits Rwanda",
    "healthcare training online",
    "medical education platform",
    "clinical skills development",
    "professional development for clinicians",
    
    // ============================================================
    // RWANDA SPECIFIC HEALTHCARE KEYWORDS
    // ============================================================
    "Rwanda health CPD",
    "CPD Rwanda",
    "continuing education Rwanda health",
    "Rwanda medical association CPD",
    "Rwanda nurses CPD",
    "Rwanda midwives council CPD",
    "Rwanda pharmacy council CPD",
    "Rwanda dental association CPD",
    "Rwanda clinical officers CPD",
    "Rwanda community health workers training",
    "Rwanda health workforce development",
    "Rwanda Ministry of Health CPD",
    "Rwanda Biomedical Centre training",
    "RBC CPD courses",
    "Rwanda healthcare training platform",
    "Kigali medical education",
    "Rwanda hospital training",
    "Rwanda nursing continuing education",
    
    // ============================================================
    // AFRICA HEALTHCARE KEYWORDS
    // ============================================================
    "Africa CPD platform",
    "East Africa medical education",
    "African healthcare professional development",
    "CPD for African doctors",
    "nursing CPD Africa",
    "midwifery education Africa",
    "clinical training Africa",
    "medical education East Africa",
    "healthcare training Rwanda",
    "African health workforce development",
    "WHO African region CPD",
    "African medical association",
    
    // ============================================================
    // COURSE CATEGORY KEYWORDS
    // ============================================================
    "maternal health courses",
    "family planning training",
    "child health courses",
    "neonatal care training",
    "infectious disease courses",
    "HIV/AIDS training",
    "tuberculosis management",
    "malaria prevention and treatment",
    "non-communicable diseases",
    "diabetes management courses",
    "hypertension training",
    "cardiovascular health CPD",
    "mental health courses",
    "psychiatry CPD",
    "emergency medicine training",
    "trauma care courses",
    "surgery CPD",
    "orthopedic training",
    "pediatric courses",
    "geriatric care training",
    "palliative care CPD",
    "oncology courses",
    "radiology training",
    "laboratory medicine CPD",
    "pharmacy courses",
    "clinical pharmacology training",
    "public health courses",
    "epidemiology training",
    "health management CPD",
    "health leadership courses",
    "health policy training",
    "research methodology CPD",
    "biostatistics courses",
    "health informatics training",
    "digital health CPD",
    "telemedicine courses",
    
    // ============================================================
    // CLINICAL SPECIALTY KEYWORDS
    // ============================================================
    "nursing CPD",
    "registered nurse training",
    "nurse practitioner courses",
    "clinical nursing education",
    "medical doctor CPD",
    "physician continuing education",
    "general practitioner training",
    "specialist doctor CPD",
    "midwifery CPD",
    "certified midwife training",
    "obstetric courses",
    "gynecology CPD",
    "pharmacy CPD",
    "clinical pharmacist training",
    "dental CPD",
    "dentist continuing education",
    "oral health courses",
    "clinical officer CPD",
    "medical assistant training",
    "community health worker CPD",
    "CHW training Rwanda",
    "health educator courses",
    "nutritionist CPD",
    "dietitian training",
    "physiotherapy CPD",
    "rehabilitation courses",
    "occupational therapy training",
    "speech therapy CPD",
    "audiology courses",
    "optometry CPD",
    "ophthalmology training",
    "medical laboratory CPD",
    "lab technician training",
    "radiology technician CPD",
    "ultrasound training",
    "ECG interpretation courses",
    "medical imaging CPD",
    "anesthesiology CPD",
    "critical care training",
    "intensive care courses",
    "emergency medicine CPD",
    "disaster medicine training",
    "triage courses",
    "resuscitation training",
    "BLS certification",
    "ACLS courses",
    "PALS training",
    "NALS certification",
    "ETAT+ courses",
    "IMCI training",
    
    // ============================================================
    // SPECIFIC DISEASE & CONDITION KEYWORDS
    // ============================================================
    "HIV management courses",
    "ART training",
    "prevention of mother to child transmission",
    "PMTCT CPD",
    "HIV testing and counseling",
    "TB management courses",
    "drug resistant TB training",
    "malaria case management",
    "severe malaria treatment",
    "malaria prevention CPD",
    "COVID-19 management",
    "pandemic response training",
    "vaccination courses",
    "immunization training",
    "EPI courses",
    "vaccine cold chain management",
    "diabetes management",
    "insulin therapy training",
    "hypertension management",
    "cardiovascular risk assessment",
    "stroke management CPD",
    "heart failure training",
    "asthma management courses",
    "COPD treatment",
    "respiratory care CPD",
    "kidney disease management",
    "dialysis training",
    "liver disease CPD",
    "hepatitis management",
    "cancer care courses",
    "oncology nursing",
    "breast cancer screening",
    "cervical cancer prevention",
    "HPV vaccination training",
    "mental health disorders",
    "depression management",
    "anxiety treatment CPD",
    "psychosis training",
    "substance abuse counseling",
    "addiction medicine CPD",
    
    // ============================================================
    // FAMILY PLANNING & REPRODUCTIVE HEALTH
    // ============================================================
    "family planning courses",
    "contraceptive methods training",
    "GATHER counseling approach",
    "long acting reversible contraception",
    "IUD insertion training",
    "implant insertion CPD",
    "injectable contraception courses",
    "oral contraceptives training",
    "emergency contraception CPD",
    "natural family planning",
    "fertility awareness methods",
    "reproductive health CPD",
    "adolescent sexual health",
    "youth friendly services",
    "postpartum family planning",
    "postnatal care courses",
    "antenatal care CPD",
    "safe motherhood training",
    "maternal mortality reduction",
    "obstetric emergency training",
    
    // ============================================================
    // CHILD HEALTH KEYWORDS
    // ============================================================
    "child health courses",
    "pediatric care training",
    "newborn care CPD",
    "essential newborn care",
    "neonatal resuscitation",
    "Helping Babies Breathe",
    "breastfeeding counseling",
    "infant and young child feeding",
    "child nutrition CPD",
    "growth monitoring training",
    "child development courses",
    "immunization training",
    "vaccine safety CPD",
    "child illness management",
    "pneumonia treatment",
    "diarrhea management",
    "oral rehydration therapy",
    "child malaria treatment",
    "pediatric HIV care",
    "child protection CPD",
    
    // ============================================================
    // PUBLIC HEALTH KEYWORDS
    // ============================================================
    "public health courses",
    "community health training",
    "health promotion CPD",
    "disease prevention courses",
    "health education training",
    "epidemiology courses",
    "disease surveillance training",
    "outbreak investigation CPD",
    "health statistics courses",
    "health research methods",
    "program monitoring and evaluation",
    "M&E training",
    "health policy courses",
    "health economics CPD",
    "health financing training",
    "universal health coverage",
    "health systems strengthening",
    "quality improvement CPD",
    "patient safety courses",
    "infection prevention control",
    "IPC training",
    "hand hygiene CPD",
    "sterilization techniques",
    "health facility management",
    "hospital administration CPD",
    
    // ============================================================
    // LEADERSHIP & MANAGEMENT KEYWORDS
    // ============================================================
    "health leadership courses",
    "healthcare management training",
    "clinical leadership CPD",
    "health team management",
    "supervisory skills training",
    "health governance courses",
    "strategic planning CPD",
    "health project management",
    "resource management training",
    "financial management for health",
    "human resources for health",
    "health workforce management",
    "performance management CPD",
    "coaching and mentoring training",
    "change management in health",
    "health quality improvement",
    "accreditation preparation",
    
    // ============================================================
    // CLINICAL SKILLS KEYWORDS
    // ============================================================
    "clinical skills training",
    "physical examination CPD",
    "patient assessment courses",
    "medical history taking",
    "diagnostic skills training",
    "point of care testing",
    "rapid diagnostic tests",
    "clinical procedures CPD",
    "wound care training",
    "suture techniques",
    "minor surgery courses",
    "sterile technique training",
    "injection safety CPD",
    "IV cannulation training",
    "blood draw techniques",
    "specimen collection CPD",
    "laboratory quality control",
    "ECG interpretation",
    "chest x-ray reading",
    "ultrasound basics",
    
    // ============================================================
    // COMMUNICATION & COUNSELING KEYWORDS
    // ============================================================
    "health communication courses",
    "patient counseling training",
    "therapeutic communication CPD",
    "breaking bad news training",
    "informed consent courses",
    "health literacy CPD",
    "cross cultural communication",
    "patient education training",
    "behavior change communication",
    "motivational interviewing",
    "risk communication CPD",
    "crisis communication training",
    "health advocacy courses",
    
    // ============================================================
    // ETHICS & PROFESSIONALISM KEYWORDS
    // ============================================================
    "medical ethics courses",
    "healthcare professionalism CPD",
    "patient rights training",
    "confidentiality in healthcare",
    "informed consent ethics",
    "end of life care ethics",
    "research ethics CPD",
    "institutional review board training",
    "conflict of interest management",
    "professional boundaries CPD",
    "whistleblowing in healthcare",
    "medical malpractice prevention",
    
    // ============================================================
    // TEACHING & TRAINING KEYWORDS
    // ============================================================
    "clinical teaching courses",
    "medical education CPD",
    "preceptorship training",
    "clinical supervision CPD",
    "bedside teaching techniques",
    "simulation training courses",
    "case based learning",
    "problem based learning CPD",
    "adult learning principles",
    "training of trainers CPD",
    "mentorship skills training",
    "assessment in medical education",
    "feedback techniques CPD",
    
    // ============================================================
    // COURSE TYPES KEYWORDS
    // ============================================================
    "online CPD courses",
    "self paced learning",
    "interactive eLearning",
    "video based courses",
    "downloadable resources",
    "quiz based assessment",
    "case study courses",
    "scenario based training",
    "simulation eLearning",
    "blended learning CPD",
    "hybrid courses",
    "live webinar CPD",
    "recorded lectures",
    "podcast CPD",
    "mobile learning healthcare",
    "offline access CPD",
    
    // ============================================================
    // CERTIFICATION KEYWORDS
    // ============================================================
    "CPD certificate",
    "verifiable certificate",
    "accredited CPD certificate",
    "digital certificate download",
    "CPD hours record",
    "professional development record",
    "continuing education units",
    "CEU credits",
    "CPD points Rwanda",
    "Rwanda health council points",
    "nursing council CPD points",
    "medical council CPD credits",
    
    // ============================================================
    // INSTITUTION KEYWORDS
    // ============================================================
    "hospital CPD training",
    "clinic staff development",
    "health center training",
    "referral hospital CPD",
    "district hospital education",
    "private clinic CPD",
    "faith based hospital training",
    "military hospital CPD",
    "university teaching hospital",
    "medical school CPD",
    "nursing school training",
    "midwifery school CPD",
    "pharmacy school education",
    "dental school CPD",
    "public health institute",
    "research institution CPD",
    "professional association CPD",
    "Rwanda Nurses Association",
    "Rwanda Medical Association",
    "Rwanda Midwives Association",
    "Rwanda Pharmaceutical Association",
    "Rwanda Dental Association",
    
    // ============================================================
    // PROFESSIONAL BODIES KEYWORDS
    // ============================================================
    "Rwanda Nursing Council",
    "Rwanda Medical and Dental Council",
    "Rwanda Pharmacy Council",
    "Rwanda Allied Health Council",
    "Rwanda Clinical Officers Council",
    "Rwanda Midwifery Council",
    "Rwanda Dental Therapists Council",
    "Rwana Optometry Council",
    "Rwanda Nutritionists Council",
    "Rwanda Physiotherapy Council",
    "Rwanda Psychology Council",
    
    // ============================================================
    // WHO & INTERNATIONAL GUIDELINES KEYWORDS
    // ============================================================
    "WHO guidelines training",
    "WHO recommended CPD",
    "global health standards",
    "international health regulations",
    "WHO Africa region CPD",
    "global health security",
    "pandemic preparedness",
    "International Health Regulations",
    "IHR training",
    "SDG health goals",
    "universal health coverage training",
    "primary health care CPD",
    
    // ============================================================
    // LONG TAIL KEYWORDS
    // ============================================================
    "best CPD platform for healthcare professionals",
    "accredited online CPD courses Rwanda",
    "how to earn CPD points online",
    "affordable CPD courses for nurses",
    "free CPD courses for doctors",
    "continuing medical education online Africa",
    "CPD requirements for Rwandan doctors",
    "mandatory CPD for healthcare workers",
    "renew license CPD credits",
    "annual CPD compliance training",
    "CPD tracking platform",
    "professional development records management",
    "healthcare career advancement courses",
    "clinical skills upgrade training",
    "evidence based practice CPD",
    "updated clinical guidelines training",
    "new treatment protocols CPD",
    "clinical best practices update",
    
    // ============================================================
    // TECHNICAL KEYWORDS
    // ============================================================
    "LMS for healthcare",
    "learning management system medical",
    "healthcare training platform",
    "medical education technology",
    "digital CPD platform",
    "mobile friendly CPD courses",
    "responsive eLearning healthcare",
    "cloud based medical training",
    "secure health education platform",
    "GDPR compliant CPD system",
    "data protected learning platform",
    
    // ============================================================
    // COURSE FORMAT KEYWORDS
    // ============================================================
    "microlearning CPD",
    "bite sized courses",
    "quick CPD modules",
    "short courses for health",
    "comprehensive training programs",
    "in depth clinical courses",
    "refresher courses healthcare",
    "update courses medical",
    "advanced clinical training",
    "specialist certificate programs",
    "diploma in clinical practice",
    
    // ============================================================
    // USER ROLE KEYWORDS
    // ============================================================
    "CPD for medical directors",
    "training for hospital administrators",
    "courses for clinic managers",
    "education for health program managers",
    "training for district health officers",
    "CPD for health center in charges",
    "courses for nursing in charges",
    "training for unit managers",
    "CPD for department heads",
    "leadership training for senior nurses",
    "management courses for clinical leads",
    
    // ============================================================
    // ASSESSMENT & EVALUATION KEYWORDS
    // ============================================================
    "pre and post test CPD",
    "knowledge assessment healthcare",
    "competency based evaluation",
    "clinical skills assessment",
    "case based assessment",
    "scenario testing CPD",
    "multiple choice quizzes medical",
    "true false questions healthcare",
    "short answer questions CPD",
    "practical assessment online",
    "simulation evaluation",
    "competency verification",
    "skill demonstration CPD",
    "portfolio assessment",
    "reflective practice CPD",
    "learning journal healthcare",
    "action plan development",
    "implementation evaluation",
    
    // ============================================================
    // ADDITIONAL HEALTHCARE KEYWORDS
    // ============================================================
    "telehealth training",
    "digital health records CPD",
    "eHealth courses",
    "mobile health training",
    "health apps for professionals",
    "clinical decision support",
    "evidence based medicine CPD",
    "systematic review training",
    "meta analysis courses",
    "clinical trial design",
    "research ethics training",
    "good clinical practice",
    "GCP certification",
    "informed consent in research",
    "data management in research",
    "scientific writing CPD",
    "manuscript preparation",
    "grant writing courses",
    "research proposal development",
    "literature search training",
    "reference management CPD",
    "EndNote training",
    "Zotero courses",
    "research collaboration skills",
    "multidisciplinary research",
    "translational research CPD",
    "implementation science",
    "knowledge translation training",
    "research impact assessment",
    
    // ============================================================
    // EMERGENCY & DISASTER KEYWORDS
    // ============================================================
    "emergency preparedness CPD",
    "disaster response training",
    "mass casualty management",
    "triage system training",
    "emergency triage assessment",
    "ETAT plus training",
    "emergency obstetric care",
    "EmOC training",
    "basic emergency care",
    "first responder training",
    "emergency first aid CPD",
    "cardiopulmonary resuscitation",
    "CPR certification",
    "automated external defibrillator",
    "AED training",
    "advanced cardiac life support",
    "pediatric advanced life support",
    "neonatal resuscitation program",
    "emergency medication management",
    "poisoning management CPD",
    "toxicology training",
    "snake bite management",
    "insect sting treatment",
    "anaphylaxis management",
    
    // ============================================================
    // SURGICAL & PROCEDURAL KEYWORDS
    // ============================================================
    "basic surgical skills",
    "surgical technique training",
    "preoperative assessment CPD",
    "postoperative care courses",
    "surgical site infection prevention",
    "wound classification training",
    "surgical instrument handling",
    "sterile field maintenance",
    "operating room safety",
    "surgical checklist compliance",
    "WHO surgical safety checklist",
    "safe surgery training",
    "anesthesia safety CPD",
    "regional anesthesia courses",
    "spinal anesthesia training",
    "general anesthesia management",
    "sedation techniques",
    "pain management CPD",
    "postoperative pain control",
    "acute pain management",
    "chronic pain treatment",
    "palliative pain relief",
    "end of life care CPD",
    "hospice care training",
    "bereavement support",
    "grief counseling courses",
    
    // ============================================================
    // LABORATORY & DIAGNOSTIC KEYWORDS
    // ============================================================
    "clinical laboratory CPD",
    "diagnostic testing training",
    "specimen collection guidelines",
    "sample transport training",
    "laboratory quality management",
    "quality control in lab",
    "lab safety CPD",
    "biohazard management",
    "chemical safety training",
    "lab equipment maintenance",
    "microscope handling CPD",
    "staining techniques training",
    "culture and sensitivity",
    "antibiotic susceptibility testing",
    "blood culture methods",
    "urinalysis training",
    "stool examination CPD",
    "sputum analysis",
    "CSF analysis training",
    "body fluid examination",
    "hematology CPD",
    "complete blood count",
    "peripheral smear examination",
    "coagulation studies",
    "clinical chemistry CPD",
    "liver function tests",
    "renal function tests",
    "cardiac markers",
    "hormone assays",
    "immunology CPD",
    "serology testing",
    "ELISA techniques",
    "rapid diagnostic tests",
    "point of care testing",
    "blood glucose monitoring",
    "HbA1c testing",
    "lipid profile analysis",
    "microbiology CPD",
    "bacterial identification",
    "fungal culture",
    "parasitology training",
    "virology CPD",
    "molecular diagnostics",
    "PCR techniques",
    "gene sequencing basics",
    "cytology CPD",
    "histopathology training",
    "frozen section technique",
    "biopsy interpretation",
    
    // ============================================================
    // RADIOLOGY & IMAGING KEYWORDS
    // ============================================================
    "radiology CPD",
    "medical imaging training",
    "x-ray interpretation courses",
    "chest x-ray reading",
    "abdominal x-ray CPD",
    "skeletal x-ray training",
    "CT scan interpretation",
    "MRI reading courses",
    "ultrasound training CPD",
    "obstetric ultrasound",
    "abdominal ultrasound",
    "pelvic ultrasound",
    "vascular ultrasound",
    "echocardiography CPD",
    "cardiac ultrasound training",
    "Doppler studies",
    "mammography CPD",
    "breast imaging training",
    "fluoroscopy CPD",
    "contrast studies training",
    "radiology safety",
    "radiation protection CPD",
    "ALARA principles",
    "radiographic positioning",
    "patient preparation imaging",
    "contrast media management",
    "anaphylaxis in radiology",
    
    // ============================================================
    // PHARMACY & MEDICATION MANAGEMENT
    // ============================================================
    "clinical pharmacy CPD",
    "medication management training",
    "prescription writing courses",
    "drug interaction checking",
    "adverse drug reaction reporting",
    "pharmacovigilance CPD",
    "medication safety training",
    "high alert medications",
    "look alike sound alike drugs",
    "medication reconciliation",
    "pharmacy compounding CPD",
    "sterile compounding training",
    "aseptic technique pharmacy",
    "chemotherapy preparation",
    "TPN compounding CPD",
    "medication counseling training",
    "patient education pharmacy",
    "adherence support CPD",
    "polypharmacy management",
    "deprescribing training",
    "therapeutic drug monitoring",
    "dosing adjustments CPD",
    "renal dosing training",
    "hepatic dosing courses",
    "pediatric dosing CPD",
    "geriatric dosing training",
    "antibiotic stewardship",
    "antimicrobial resistance",
    "appropriate antibiotic use",
    "antimicrobial stewardship CPD",
    "AMS training",
    
    // ============================================================
    // PHYSIOTHERAPY & REHABILITATION
    // ============================================================
    "physiotherapy CPD",
    "rehabilitation training",
    "physical therapy techniques",
    "manual therapy CPD",
    "joint mobilization training",
    "muscle energy techniques",
    "stretching protocols",
    "therapeutic exercise CPD",
    "strengthening programs",
    "balance training courses",
    "gait analysis CPD",
    "walking aids training",
    "wheelchair prescription",
    "orthotic management",
    "prosthetic training",
    "neurological physiotherapy",
    "stroke rehabilitation CPD",
    "spinal cord injury rehab",
    "traumatic brain injury rehab",
    "Parkinson's physiotherapy",
    "multiple sclerosis rehab",
    "musculoskeletal physiotherapy",
    "back pain management",
    "neck pain treatment",
    "shoulder rehabilitation",
    "knee rehab CPD",
    "ankle sprain management",
    "sports physiotherapy",
    "athletic training CPD",
    "injury prevention courses",
    "return to play protocols",
    "cardiorespiratory physiotherapy",
    "chest physiotherapy CPD",
    "breathing exercises",
    "airway clearance techniques",
    "pulmonary rehabilitation",
    "cardiac rehabilitation CPD",
    "post surgical physiotherapy",
    "pre operative preparation",
    "post op mobilization",
    "joint replacement rehab",
    "fracture rehabilitation",
    "pediatric physiotherapy",
    "child development CPD",
    "gross motor skills",
    "fine motor development",
    "cerebral palsy management",
    "muscular dystrophy rehab",
    "geriatric physiotherapy",
    "fall prevention training",
    "osteoporosis management",
    "arthritis rehabilitation",
    "aquatic therapy CPD",
    "hydrotherapy training",
    "electrotherapy CPD",
    "TENS application",
    "ultrasound therapy",
    "laser therapy training",
    "shockwave therapy CPD",
    "acupuncture in physiotherapy",
    "dry needling training",
    "kinesiology taping CPD",
    "rock tape techniques",
    "myofascial release",
    "trigger point therapy",
    "massage therapy CPD",
    "sports massage training",
    "clinical massage techniques",
    "lymphatic drainage CPD",
    "edema management",
    "wound care physiotherapy",
    "pressure ulcer prevention",
    "scar management CPD",
    "burn rehabilitation",
    
    // ============================================================
    // OCCUPATIONAL THERAPY KEYWORDS
    // ============================================================
    "occupational therapy CPD",
    "activities of daily living",
    "ADL training",
    "instrumental ADL courses",
    "adaptive equipment CPD",
    "home modification training",
    "wheelchair seating",
    "positioning techniques",
    "splinting CPD",
    "orthosis fabrication",
    "hand therapy training",
    "fine motor rehabilitation",
    "sensory integration CPD",
    "sensory processing disorder",
    "autism OT training",
    "developmental delay therapy",
    "learning disability support",
    "cognitive rehabilitation CPD",
    "memory training techniques",
    "executive function training",
    "attention improvement",
    "visual perceptual training",
    "workplace ergonomics CPD",
    "job site assessment",
    "return to work programs",
    "vocational rehabilitation",
    "driving assessment CPD",
    "community reintegration",
    "social participation training",
    "leisure activities therapy",
    "environmental modification",
    "universal design CPD",
    "aging in place training",
    "low vision rehabilitation",
    "blindness adaptation",
    "hearing impairment CPD",
    "deaf communication",
    "mental health OT",
    "psychosocial rehabilitation",
    "anxiety management activities",
    "depression intervention",
    "stress reduction techniques",
    
    // ============================================================
    // SPEECH THERAPY KEYWORDS
    // ============================================================
    "speech therapy CPD",
    "language therapy training",
    "articulation disorders",
    "phonological processing",
    "fluency disorders CPD",
    "stuttering therapy",
    "voice disorders training",
    "vocal cord dysfunction",
    "resonance disorders CPD",
    "cleft palate speech",
    "apraxia of speech",
    "dysarthria management",
    "aphasia therapy CPD",
    "stroke communication",
    "cognitive communication disorders",
    "social communication training",
    "pragmatic language skills",
    "augmentative communication",
    "AAC devices CPD",
    "picture exchange system",
    "sign language training",
    "swallowing disorders CPD",
    "dysphagia management",
    "videofluoroscopic swallow study",
    "FEES training",
    "feeding therapy CPD",
    "pediatric feeding disorders",
    "oral motor exercises",
    "sensory feeding issues",
    "pick eating intervention",
    "tube feeding transition",
    "dysphagia diet levels",
    "thickened liquids training",
    "chin tuck posture",
    "effortful swallow technique",
    "Mendelsohn maneuver",
    "Shaker exercise CPD",
    "respiratory muscle training",
    "cough strength training",
    "expiratory muscle strength",
    "neuromuscular electrical stimulation",
    "vital stim training",
    "Lee Silverman voice treatment",
    "LSVT LOUD CPD",
    "speak out therapy",
    "speech intelligibility training",
    "rate reduction techniques",
    "pacing boards CPD",
    "letter board training",
    "communication partner training",
    "family education CPD",
    
    // ============================================================
    // NUTRITION & DIETETICS KEYWORDS
    // ============================================================
    "clinical nutrition CPD",
    "dietetics training",
    "therapeutic diets courses",
    "enteral nutrition CPD",
    "tube feeding management",
    "parenteral nutrition training",
    "TPN compounding",
    "nutrition assessment CPD",
    "malnutrition screening",
    "nutritional status evaluation",
    "body composition analysis",
    "dietary counseling CPD",
    "patient education nutrition",
    "meal planning training",
    "therapeutic menu development",
    "diabetes nutrition therapy",
    "carbohydrate counting CPD",
    "insulin to carb ratio",
    "renal diet training",
    "low protein diet",
    "phosphorus management",
    "potassium restriction",
    "fluid restriction CPD",
    "hemodialysis nutrition",
    "peritoneal dialysis diet",
    "cardiovascular nutrition",
    "low sodium diet CPD",
    "DASH diet training",
    "Mediterranean diet",
    "lipid management nutrition",
    "cholesterol lowering diet",
    "gastrointestinal nutrition",
    "IBD diet therapy",
    "IBS management CPD",
    "FODMAP diet training",
    "celiac disease diet",
    "gluten free counseling",
    "food allergy management",
    "allergen avoidance CPD",
    "anaphylaxis prevention",
    "maternal nutrition CPD",
    "pregnancy diet counseling",
    "lactation nutrition",
    "breastfeeding support",
    "postnatal nutrition training",
    "pediatric nutrition CPD",
    "infant feeding guidelines",
    "baby led weaning",
    "complementary feeding",
    "child growth monitoring",
    "adolescent nutrition CPD",
    "eating disorders treatment",
    "anorexia nervosa management",
    "bulimia nervosa therapy",
    "binge eating disorder",
    "geriatric nutrition CPD",
    "elderly malnutrition",
    "sarcopenia prevention",
    "protein needs aging",
    "nutrition supplements CPD",
    "oral nutrition supplements",
    "vitamin D supplementation",
    "calcium requirements",
    "iron deficiency anemia",
    "B12 deficiency management",
    "zinc supplementation CPD",
    "sports nutrition CPD",
    "athletic performance",
    "pre workout fueling",
    "post workout recovery",
    "hydration strategies",
    "electrolyte balance",
    "body weight management",
    "weight loss counseling CPD",
    "obesity management",
    "bariatric surgery nutrition",
    "pre op diet preparation",
    "post op diet progression",
    "protein supplements CPD",
    "meal replacement therapy",
    "very low calorie diet",
    "intermittent fasting CPD",
    "ketogenic diet therapy",
    "low carb diet training",
    "paleo diet counseling",
    "vegan nutrition CPD",
    "plant based diet",
    "vegetarian meal planning",
    "food service management",
    "kitchen sanitation CPD",
    "food safety training",
    "HACCP principles",
    "temperature monitoring",
    "cross contamination prevention",
    "allergen control CPD",
    "food labeling training",
    "nutrition labeling CPD",
    "calorie counting",
    "macro tracking training",
    "micro nutrient analysis",
    "dietary supplement safety",
    "herbal medicine interactions",
    "nutraceuticals CPD",
    "functional foods training",
    "probiotics and prebiotics",
    "gut microbiome health",
    
    // ============================================================
    // DENTISTRY & ORAL HEALTH KEYWORDS
    // ============================================================
    "dental CPD",
    "oral health training",
    "dentistry continuing education",
    "restorative dentistry CPD",
    "composite fillings training",
    "amalgam restoration courses",
    "crown and bridge CPD",
    "dental veneers training",
    "inlay and onlay courses",
    "endodontics CPD",
    "root canal therapy",
    "pulp capping training",
    "apicoectomy courses",
    "surgical endodontics CPD",
    "periodontics CPD",
    "gum disease management",
    "scaling and root planing",
    "periodontal surgery training",
    "dental implantology CPD",
    "implant placement courses",
    "implant prosthetics training",
    "bone grafting CPD",
    "sinus lift procedures",
    "ridge augmentation courses",
    "orthodontics CPD",
    "braces techniques training",
    "clear aligner therapy",
    "retainer fabrication CPD",
    "space maintainers courses",
    "pediatric dentistry CPD",
    "child dental care",
    "fluoride varnish application",
    "dental sealants training",
    "space management CPD",
    "oral surgery CPD",
    "tooth extraction techniques",
    "wisdom tooth removal",
    "alveoloplasty training",
    "biopsy procedures CPD",
    "prosthodontics CPD",
    "complete dentures training",
    "partial dentures courses",
    "immediate dentures CPD",
    "overdentures training",
    "dental materials CPD",
    "impression techniques",
    "bite registration training",
    "articulator mounting CPD",
    "ceramic layering courses",
    "digital dentistry CPD",
    "CAD CAM dentistry",
    "intraoral scanning training",
    "3D printing dental CPD",
    "digital smile design",
    "cone beam CT interpretation",
    "dental radiology CPD",
    "panoramic x ray reading",
    "periapical radiograph",
    "bitewing interpretation",
    "occlusal radiograph CPD",
    "dental radiography safety",
    "radiation protection dentistry",
    "patient positioning CPD",
    "infection control dental",
    "sterilization techniques",
    "dental unit disinfection",
    "instrument processing CPD",
    "personal protective equipment",
    "hand hygiene dental",
    "surface disinfection CPD",
    "dental waste management",
    "sharps disposal training",
    "dental emergencies CPD",
    "toothache management",
    "dental trauma care",
    "avulsed tooth management",
    "luxation injury CPD",
    "dental abscess treatment",
    "cellulitis management",
    "airway management dental",
    "anaphylaxis in dentistry",
    "medical emergencies CPD",
    "syncope management",
    "hypertensive crisis",
    "hypoglycemia treatment",
    "seizure management CPD",
    "conscious sedation dental",
    "nitrous oxide administration",
    "oral sedation techniques",
    "IV sedation monitoring",
    "local anesthesia CPD",
    "injection techniques",
    "nerve block training",
    "infiltration methods CPD",
    "complications management",
    "dental pharmacology CPD",
    "antibiotics in dentistry",
    "analgesics prescribing",
    "antimicrobial prophylaxis",
    "drug interactions dental",
    "special care dentistry CPD",
    "geriatric dental care",
    "special needs patients",
    "medically compromised CPD",
    "dental anxiety management",
    "behavior management CPD",
    "tell show do technique",
    "positive reinforcement",
    "distraction techniques CPD",
    "preventive dentistry CPD",
    "oral hygiene instruction",
    "plaque control training",
    "diet counseling dental",
    "smoking cessation CPD",
    "tobacco cessation dental",
    "oral cancer screening CPD",
    "soft tissue examination",
    "biopsy indication training",
    "referral guidelines CPD",
    
    // ============================================================
    // OPTOMETRY & OPHTHALMOLOGY KEYWORDS
    // ============================================================
    "optometry CPD",
    "ophthalmology training",
    "eye care continuing education",
    "refraction techniques CPD",
    "retinoscopy training",
    "autorefractor use courses",
    "subjective refraction CPD",
    "cycloplegic refraction training",
    "pediatric refraction CPD",
    "contact lens fitting CPD",
    "soft contact lenses training",
    "rigid gas permeable CPD",
    "scleral lens fitting courses",
    "keratoconus management CPD",
    "orthokeratology training",
    "low vision CPD",
    "visual aids prescription",
    "magnification devices",
    "telescopic lenses CPD",
    "electronic vision aids",
    "vision rehabilitation CPD",
    "orientation and mobility",
    "activities of daily living",
    "glaucoma CPD",
    "tonometry training",
    "visual field testing",
    "optic disc examination CPD",
    "gonioscopy courses",
    "retinal imaging CPD",
    "fundus photography",
    "OCT interpretation",
    "fluorescein angiography",
    "diabetic retinopathy CPD",
    "retinopathy screening",
    "laser treatment training",
    "anti VEGF therapy CPD",
    "macular degeneration CPD",
    "dry AMD management",
    "wet AMD treatment",
    "photodynamic therapy CPD",
    "cataract CPD",
    "cataract surgery training",
    "phacoemulsification courses",
    "IOL calculation CPD",
    "multifocal lenses training",
    "post cataract care CPD",
    "pediatric ophthalmology CPD",
    "strabismus management",
    "amblyopia treatment",
    "patching therapy CPD",
    "atropine penalization",
    "congenital cataract CPD",
    "retinopathy of prematurity",
    "ROP screening CPD",
    "neuro ophthalmology CPD",
    "optic neuritis management",
    "papilledema training",
    "visual pathway lesions",
    "pupil abnormalities CPD",
    "eye emergencies CPD",
    "corneal abrasion",
    "foreign body removal",
    "chemical eye injury CPD",
    "traumatic hyphema",
    "orbital fracture CPD",
    "retinal detachment",
    "acute glaucoma CPD",
    "endophthalmitis management",
    "temporal arteritis CPD",
    "ocular trauma training",
    "orbital cellulitis CPD",
    "uveitis management CPD",
    "anterior uveitis",
    "posterior uveitis",
    "panuveitis treatment",
    "systemic disease eye",
    "thyroid eye disease CPD",
    "Sjogren syndrome",
    "rheumatoid arthritis eye",
    "systemic lupus CPD",
    "eye medication CPD",
    "topical antibiotics",
    "steroid eye drops",
    "antiglaucoma medications",
    "cycloplegic agents",
    "ocular hygiene CPD",
    "contact lens care",
    "eyelid hygiene training",
    "warm compress technique",
    "artificial tears CPD",
    
    // ============================================================
    // PSYCHOLOGY & MENTAL HEALTH KEYWORDS
    // ============================================================
    "clinical psychology CPD",
    "mental health training",
    "psychological assessment CPD",
    "diagnostic interview training",
    "cognitive assessment courses",
    "personality testing CPD",
    "intelligence testing training",
    "neuropsychological assessment",
    "psychotherapy CPD",
    "cognitive behavioral therapy",
    "CBT training courses",
    "dialectical behavior therapy",
    "DBT training CPD",
    "acceptance commitment therapy",
    "ACT training courses",
    "mindfulness based therapy",
    "MBCT training CPD",
    "psychodynamic therapy",
    "psychoanalytic therapy CPD",
    "humanistic therapy training",
    "person centered approach",
    "gestalt therapy CPD",
    "existential therapy training",
    "family therapy CPD",
    "couples counseling",
    "marital therapy training",
    "group therapy CPD",
    "support group facilitation",
    "psychoeducation groups",
    "trauma therapy CPD",
    "PTSD treatment training",
    "EMDR therapy courses",
    "prolonged exposure CPD",
    "trauma focused CBT",
    "child psychology CPD",
    "play therapy training",
    "art therapy courses",
    "sandplay therapy CPD",
    "adolescent psychology",
    "teen mental health CPD",
    "developmental psychology",
    "attachment theory CPD",
    "parent child interaction",
    "PCIT training courses",
    "school psychology CPD",
    "educational assessment",
    "learning disability evaluation",
    "behavioral intervention",
    "applied behavior analysis",
    "ABA therapy CPD",
    "positive behavior support",
    "functional assessment CPD",
    "crisis intervention CPD",
    "suicide risk assessment",
    "self harm management",
    "acute stress reaction",
    "psychological first aid",
    "substance abuse counseling",
    "addiction treatment CPD",
    "motivational interviewing",
    "harm reduction strategies",
    "relapse prevention CPD",
    "12 step facilitation",
    "eating disorders CPD",
    "anorexia treatment",
    "bulimia nervosa therapy",
    "binge eating disorder",
    "mood disorders CPD",
    "depression treatment",
    "bipolar disorder management",
    "seasonal affective disorder",
    "anxiety disorders CPD",
    "panic disorder treatment",
    "generalized anxiety",
    "social anxiety therapy",
    "specific phobias CPD",
    "OCD treatment CPD",
    "exposure response prevention",
    "hoarding disorder therapy",
    "body dysmorphic disorder",
    "psychotic disorders CPD",
    "schizophrenia management",
    "delusional disorder therapy",
    "brief psychotic disorder",
    "personality disorders CPD",
    "borderline personality",
    "narcissistic personality",
    "antisocial personality",
    "neurodevelopmental disorders",
    "ADHD management CPD",
    "autism spectrum disorder",
    "ASD interventions",
    "Tourette syndrome CPD",
    "intellectual disability",
    "neurocognitive disorders",
    "dementia care CPD",
    "Alzheimer's management",
    "vascular dementia CPD",
    "Lewy body dementia",
    "frontotemporal dementia",
    "sleep disorders CPD",
    "insomnia treatment",
    "CBT for insomnia",
    "sleep hygiene training",
    "circadian rhythm disorders",
    "parasomnia management",
    "forensic psychology CPD",
    "criminal behavior assessment",
    "risk assessment training",
    "competency evaluation CPD",
    "insanity defense",
    "victim psychology CPD",
    "trauma informed care",
    "vicarious trauma prevention",
    "compassion fatigue CPD",
    "burnout prevention",
    "resilience training CPD",
    "self care strategies",
    "professional boundaries",
    "ethical practice CPD",
    "confidentiality training",
    "informed consent CPD",
    "dual relationships",
    "cultural competence CPD",
    "cross cultural therapy",
    "diversity awareness",
    "inclusive practice CPD",
    "LGBTQ affirmative therapy",
    "trauma informed care CPD",
    "strength based approach",
    "recovery oriented practice",
    
    // ============================================================
    // HEALTH MANAGEMENT & ADMINISTRATION
    // ============================================================
    "health management CPD",
    "hospital administration training",
    "healthcare leadership courses",
    "clinical governance CPD",
    "quality improvement healthcare",
    "patient safety training",
    "risk management health",
    "health policy CPD",
    "strategic planning healthcare",
    "operational management CPD",
    "financial management health",
    "budgeting for health",
    "health economics CPD",
    "cost effectiveness analysis",
    "resource allocation training",
    "human resource management",
    "health workforce planning",
    "staff recruitment CPD",
    "performance management health",
    "supervisory skills CPD",
    "team leadership training",
    "conflict resolution health",
    "change management CPD",
    "organizational development",
    "health informatics CPD",
    "health information systems",
    "electronic medical records",
    "EMR implementation",
    "data quality management",
    "health data analytics",
    "business intelligence health",
    "performance indicators CPD",
    "balanced scorecard",
    "key performance indicators",
    "dashboard reporting CPD",
    "health monitoring evaluation",
    "M and E framework",
    "logical framework analysis",
    "theory of change CPD",
    "impact evaluation methods",
    "quality assurance health",
    "accreditation preparation",
    "standards compliance CPD",
    "audit and inspection",
    "corrective action planning",
    "continuous quality improvement",
    "PDSA cycles CPD",
    "lean management health",
    "Six Sigma healthcare",
    "process improvement CPD",
    "workflow optimization",
    "waste reduction health",
    "efficiency improvement CPD",
    "supply chain management",
    "health logistics CPD",
    "pharmaceutical supply",
    "medical equipment management",
    "inventory control CPD",
    "procurement procedures",
    "tendering process health",
    "contract management CPD",
    "vendor evaluation training",
    "facility management health",
    "hospital maintenance CPD",
    "infrastructure planning",
    "space utilization training",
    "environmental services CPD",
    "health marketing CPD",
    "community engagement",
    "stakeholder management",
    "partnership development",
    "advocacy skills CPD",
    "health communication",
    "social marketing health",
    "behavior change communication",
    "public relations health",
    "media relations CPD",
    "crisis communication health",
    "risk communication CPD",
    "health campaigns CPD",
    "awareness raising",
    "health promotion strategies",
    "social mobilization CPD",
    "community participation",
    "patient engagement CPD",
    "client centered care",
    "patient satisfaction measurement",
    "complaints handling CPD",
    "feedback systems",
    "patient advocacy CPD",
    "health law and ethics",
    "medical law CPD",
    "patient rights training",
    "informed consent law",
    "negligence prevention",
    "malpractice risk management",
    "legal documentation CPD",
    "medical records law",
    "privacy regulations CPD",
    "data protection health",
    "HIPAA compliance training",
    "confidentiality law",
    "mandatory reporting CPD",
    "child protection law",
    "elder abuse reporting",
    "domestic violence CPD",
    "health insurance CPD",
    "insurance claims processing",
    "billing procedures health",
    "coding systems CPD",
    "ICD 10 training",
    "CPT coding courses",
    "DRG classification CPD",
    "reimbursement mechanisms",
    "insurance verification CPD",
    "pre authorization process",
    "claim denial management",
    "appeals process CPD",
    "third party administration",
    "managed care CPD",
    "health maintenance organization",
    "preferred provider network",
    "point of service plans",
    "patient financial counseling",
    "sliding fee scales CPD",
    "charity care policies",
    "bad debt management",
    "revenue cycle management",
    "billing compliance CPD",
    "fraud prevention healthcare",
    "abuse detection training",
    "waste reduction CPD",
    "false claims act",
    "compliance programs CPD",
    "corporate integrity",
    "ethics and compliance",
    "code of conduct training",
    "conflict of interest CPD",
    "gift policy training",
    "anti kickback laws",
    "Stark law compliance",
    "self disclosure protocol",
    "investigation procedures CPD",
    "corrective action CPD",
    "disciplinary process",
    "termination procedures",
    "appeal rights CPD",
    "grievance mechanism",
    "ombudsman program",
    "patient safety organization",
    "root cause analysis CPD",
    "sentinel event review",
    "failure mode effects",
    "FMEA training CPD",
    "hazard analysis",
    "risk assessment tools",
    "incident reporting CPD",
    "near miss reporting",
    "adverse event management",
    "disclosure protocols CPD",
    "apology legislation",
    "second victim support",
    "peer review process CPD",
    "clinical peer review",
    "morbidity mortality conference",
    "case review committees",
    "quality committee structure",
    "board oversight CPD",
    "governance training",
    "fiduciary responsibility",
    "board composition CPD",
    "committee structure",
    "policy development CPD",
    "procedure writing",
    "protocol development",
    "guideline creation",
    "standard operating procedure",
    "work instruction CPD",
    "form development",
    "template design",
    "checklist creation CPD",
    "job aid development",
    "training material CPD",
    "competency assessment",
    "skills verification",
    "credentialing process CPD",
    "privileging procedure",
    "recredentialing CPD",
    "license verification",
    "certification tracking",
    "education record management",
    "continuing education tracking",
    "CPD compliance monitoring",
    "license renewal CPD",
    "professional development plan",
    "career ladder CPD",
    "succession planning",
    "talent management CPD",
    "leadership development",
    "management training CPD",
    "executive education",
    "board development CPD",
    "strategic planning retreat",
    "vision and mission CPD",
    "values development",
    "culture transformation",
    "organizational change CPD",
    "performance excellence",
    "award preparation CPD",
    "baldrige criteria",
    "EFQM model CPD",
    "ISO certification",
    "quality award application",
    "benchmarking CPD",
    "best practice sharing",
    "peer comparison",
    "industry standards CPD",
    "regulatory compliance",
    "licensure requirements",
    "accreditation standards",
    "deficiency correction CPD",
    "survey readiness",
    "mock survey training",
    "continuous readiness CPD",
    "compliance calendar",
    "deadline tracking",
    "report submission CPD",
    "data reporting",
    "statistical reporting",
    "annual report preparation",
    "board reporting CPD",
    "management reporting",
    "operational dashboard",
    "executive summary CPD",
    "balanced scorecard report",
    "performance dashboard",
    "quality scorecard CPD",
    "patient satisfaction report",
    "employee engagement survey",
    "turnover analysis CPD",
    "retention strategies",
    "recruitment planning",
    "onboarding program CPD",
    "orientation training",
    "mentorship program CPD",
    "preceptorship training",
    "coaching skills CPD",
    "feedback techniques",
    "performance appraisal CPD",
    "goal setting training",
    "objective development",
    "KPI definition CPD",
    "metric selection",
    "data collection method",
    "data verification CPD",
    "data validation",
    "data cleaning CPD",
    "data analysis training",
    "statistical software",
    "SPSS training CPD",
    "Excel for health",
    "data visualization CPD",
    "chart creation",
    "graph interpretation",
    "dashboard design CPD",
    "report writing CPD",
    "executive summary",
    "technical report",
    "narrative reporting CPD",
    "visual reporting",
    "infographic creation",
    "presentation skills CPD",
    "public speaking",
    "meeting facilitation",
    "workshop delivery CPD",
    "training facilitation",
    "adult education methods",
    "participatory learning CPD",
    "active learning techniques",
    "case study method",
    "problem based learning CPD",
    "scenario based training",
    "role play exercises",
    "simulation training CPD",
    "mock scenarios",
    "drill exercises",
    "tabletop exercises",
    "full scale exercise CPD",
    "after action review",
    "debriefing techniques",
    "lessons learned CPD",
    "improvement planning",
    "action item tracking",
    "follow up verification",
    "sustainability planning CPD",
    "maintenance strategies",
    "continuous improvement CPD",
    "kaizen training",
    "small tests of change",
    "rapid cycle improvement",
    "PDCA methodology CPD",
    "root cause identification",
    "countermeasure development",
    "implementation planning CPD",
    "change management tools",
    "communication planning",
    "stakeholder analysis",
    "influence mapping CPD",
    "resistance management",
    "adoption strategies CPD",
    "spread and scale",
    "replication planning",
    "adaptation methods",
    "contextualization CPD",
    "localization strategies",
    "customization approach",
    "tailoring techniques CPD",
    "flexible implementation",
    "adaptive management",
    "responsive planning CPD",
    "agile methodology",
    "iterative development",
    "sprint planning CPD",
    "scrum training",
    "kanban method",
    "lean startup CPD",
    "design thinking",
    "human centered design",
    "user experience CPD",
    "customer journey mapping",
    "service blueprinting",
    "process mapping CPD",
    "value stream mapping",
    "swimlane diagram",
    "flowchart creation",
    "SIPOC diagram CPD",
    "cause effect diagram",
    "fishbone analysis",
    "pareto chart CPD",
    "histogram creation",
    "control chart CPD",
    "run chart analysis",
    "scatter plot CPD",
    "box plot interpretation",
    "statistical process control",
    "SPC training CPD",
    "capability analysis",
    "process sigma calculation",
    "defect measurement CPD",
    "yield calculation",
    "throughput analysis CPD",
    "cycle time reduction",
    "wait time elimination",
    "bottleneck identification",
    "theory of constraints CPD",
    "drum buffer rope",
    "critical chain method",
    "goldratt principles CPD",
    "optimization techniques",
    "resource leveling",
    "capacity planning CPD",
    "demand forecasting",
    "utilization analysis",
    "efficiency calculation CPD",
    "productivity measurement",
    "performance ratio",
    "output per input CPD",
    "cost per unit",
    "expense analysis",
    "budget variance CPD",
    "forecast accuracy",
    "trend analysis CPD",
    "pattern recognition",
    "anomaly detection",
    "outlier identification CPD",
    "correlation analysis",
    "regression analysis",
    "predictive modeling CPD",
    "forecasting methods",
    "time series analysis",
    "seasonal adjustment CPD",
    "smoothing techniques",
    "moving average CPD",
    "exponential smoothing",
    "holt winters method",
    "ARIMA modeling CPD",
    "machine learning basics",
    "artificial intelligence health",
    "predictive analytics CPD",
    "prescriptive analytics",
    "diagnostic analytics",
    "descriptive analytics CPD",
    "business intelligence",
    "data warehousing CPD",
    "data mining",
    "text mining CPD",
    "natural language processing",
    "sentiment analysis CPD",
    "social media monitoring",
    "web analytics CPD",
    "digital marketing analytics",
    "campaign tracking CPD",
    "conversion optimization",
    "funnel analysis CPD",
    "attribution modeling",
    "customer lifetime value",
    "retention analysis CPD",
    "churn prediction",
    "loyalty measurement",
    "net promoter score CPD",
    "customer satisfaction",
    "service quality measurement",
    "SERVQUAL training CPD",
    "gap analysis",
    "expectation perception",
    "service improvement CPD",
    "moment of truth",
    "service recovery CPD",
    "complaint resolution",
    "apology techniques",
    "compensation strategies CPD",
    "follow up process",
    "customer delight CPD",
    "exceeding expectations",
    "value added service",
    "extra mile CPD",
    "wow factor",
    "surprise and delight",
    "customer advocacy CPD",
    "referral generation",
    "word of mouth CPD",
    "testimonial collection",
    "case study development",
    "success story writing CPD",
    "impact reporting",
    "outcome measurement",
    "result documentation CPD",
    "evidence collection",
    "proof of concept CPD",
    "pilot testing",
    "feasibility study",
    "cost benefit analysis CPD",
    "return on investment",
    "social return CPD",
    "economic evaluation",
    "cost utility analysis",
    "quality adjusted life year",
    "QALY calculation CPD",
    "disability adjusted life year",
    "DALY measurement",
    "burden of disease CPD",
    "mortality measurement",
    "morbidity statistics",
    "prevalence calculation CPD",
    "incidence rate",
    "risk ratio calculation",
    "odds ratio CPD",
    "confidence interval",
    "p value interpretation",
    "statistical significance CPD",
    "power analysis",
    "sample size calculation",
    "study design CPD",
    "randomized controlled trial",
    "cohort study design",
    "case control study CPD",
    "cross sectional study",
    "longitudinal study CPD",
    "qualitative research",
    "focus group method",
    "key informant interview",
    "participant observation CPD",
    "ethnographic study",
    "grounded theory CPD",
    "phenomenological study",
    "action research CPD",
    "participatory research",
    "community based research",
    "appreciative inquiry CPD",
    "asset based approach",
    "strength based method",
    "positive deviance CPD",
    "solution focused approach",
    "brief intervention CPD",
    "motiv enhancement",
    "stages of change",
    "transtheoretical model CPD",
    "health belief model",
    "social cognitive theory",
    "theory of planned behavior CPD",
    "transtheoretical model",
    "precaution adoption model",
    "protection motivation CPD",
    "health action process",
    "implementation intention",
    "action planning CPD",
    "coping planning",
    "relapse prevention CPD",
    "maintenance strategies",
    "long term support",
    "booster session CPD",
    "refresher training",
    "update course CPD",
    "advanced training",
    "specialist certification CPD",
    "master class",
    "expert workshop CPD",
    "international conference",
    "webinar attendance",
    "online seminar CPD",
    "virtual conference",
    "digital learning CPD",
    "asynchronous learning",
    "synchronous learning CPD",
    "blended learning",
    "hybrid training CPD",
    "flipped classroom",
    "inverted teaching",
    "peer instruction CPD",
    "collaborative learning",
    "cooperative learning CPD",
    "team based learning",
    "problem based learning CPD",
    "project based learning",
    "inquiry based learning CPD",
    "discovery learning",
    "experiential learning CPD",
    "hands on training",
    "practical skills CPD",
    "clinical simulation",
    "manikin training CPD",
    "standardized patient",
    "role play with actor",
    "virtual reality training",
    "VR simulation CPD",
    "augmented reality",
    "AR training CPD",
    "mixed reality learning",
    "immersive technology",
    "serious games CPD",
    "gamification training",
    "point scoring system",
    "badge earning CPD",
    "leaderboard competition",
    "achievement unlocking",
    "level progression CPD",
    "quest based learning",
    "challenge completion CPD",
    "mission achievement",
    "skill tree development",
    "competency unlocking CPD",
    "knowledge verification",
    "skill demonstration CPD",
    "practical assessment",
    "clinical examination CPD",
    "OSCE training",
    "objective structured exam",
    "clinical skills testing CPD",
    "bedside assessment",
    "direct observation CPD",
    "mini CEX",
    "case based discussion",
    "multisource feedback CPD",
    "360 degree evaluation",
    "peer assessment CPD",
    "self assessment",
    "reflective practice CPD",
    "portfolio compilation",
    "learning log CPD",
    "reflective journal",
    "critical incident CPD",
    "significant event analysis",
    "case reflection CPD",
    "action learning set",
    "supervision group CPD",
    "peer support group",
    "mastermind group CPD",
    "community of practice",
    "professional learning community",
    "network of practice CPD",
    "knowledge sharing",
    "expert exchange CPD",
    "mentoring program",
    "coaching relationship CPD",
    "supervisory support",
    "clinical supervision CPD",
    "professional mentorship",
    "career guidance CPD",
    "role modeling",
    "shadowing opportunity CPD",
    "observership program",
    "clinical attachment CPD",
    "elective placement",
    "exchange program CPD",
    "international rotation",
    "fellowship training CPD",
    "residency program",
    "specialist training CPD",
    "subspecialty fellowship",
    "advanced practice CPD",
    "consultant development",
    "leadership fellowship CPD",
    "management training",
    "executive education CPD",
    "board certification",
    "professional licensure CPD",
    "registration renewal",
    "license maintenance CPD",
    "practice privilege",
    "credential maintenance CPD",
    "recertification exam",
    "revalidation process CPD",
    "appraisal system",
    "annual review CPD",
    "performance assessment",
    "competency evaluation CPD",
    "capability assessment",
    "skill verification CPD",
    "knowledge test",
    "written examination CPD",
    "oral examination",
    "viva voce CPD",
    "practical demonstration",
    "skill station CPD",
    "procedure log",
    "case log CPD",
    "procedure count",
    "experience documentation CPD",
    "volume tracking",
    "outcome monitoring CPD",
    "complication rate",
    "success rate CPD",
    "patient outcome",
    "treatment efficacy CPD",
    "intervention effectiveness",
    "program evaluation CPD",
    "project assessment",
    "initiative review CPD",
    "service audit",
    "clinical audit CPD",
    "quality audit",
    "compliance audit CPD",
    "financial audit",
    "performance audit CPD",
    "system audit",
    "process audit CPD",
    "product audit",
    "supplier audit CPD",
    "regulatory inspection",
    "accreditation survey CPD",
    "licensure review",
    "certification audit CPD",
    "surveillance visit",
    "follow up inspection CPD",
    "corrective action",
    "preventive action CPD",
    "CAPA management",
    "non conformance handling",
    "deviation management CPD",
    "exception reporting",
    "waiver request CPD",
    "exemption application",
    "variance approval CPD",
    "change control",
    "modification request CPD",
    "amendment process",
    "revision management CPD",
    "version control",
    "document management CPD",
    "record keeping",
    "archive management CPD",
    "retention policy",
    "destruction procedure CPD",
    "disposal method",
    "shredding process CPD",
    "secure deletion",
    "data purge CPD",
    "information lifecycle",
    "records retention CPD",
    "legal hold",
    "litigation support CPD",
    "discovery process",
    "evidence preservation CPD",
    "forensic collection",
    "chain of custody CPD",
    "evidence handling",
    "secure storage CPD",
    "access control",
    "authorization system CPD",
    "permission management",
    "role based access CPD",
    "user authentication",
    "multi factor authentication",
    "password policy CPD",
    "account management",
    "session control CPD",
    "activity logging",
    "audit trail CPD",
    "system monitoring",
    "intrusion detection CPD",
    "security incident",
    "breach response CPD",
    "disaster recovery",
    "business continuity CPD",
    "backup procedure",
    "restoration process CPD",
    "failover system",
    "redundancy planning CPD",
    "high availability",
    "load balancing CPD",
    "scalability planning",
    "capacity management CPD",
    "performance optimization",
    "system tuning CPD",
    "resource allocation",
    "memory management CPD",
    "storage optimization",
    "network configuration CPD",
    "bandwidth planning",
    "latency reduction CPD",
    "throughput improvement",
    "response time CPD",
    "user experience",
    "interface design CPD",
    "usability testing",
    "accessibility compliance CPD",
    "WCAG guidelines",
    "screen reader support",
    "keyboard navigation CPD",
    "color contrast",
    "font readability CPD",
    "responsive design",
    "mobile optimization CPD",
    "cross browser compatibility",
    "device adaptation CPD",
    "touch interface",
    "voice control CPD",
    "assistive technology",
    "adaptive equipment CPD",
    "universal design",
    "inclusive design CPD",
    "accessible content",
    "alternative text CPD",
    "captioning service",
    "audio description CPD",
    "sign language interpretation",
    "translation service CPD",
    "language support",
    "cultural adaptation CPD",
    "localization service",
    "regional variation CPD",
    "contextualization",
    "customization option CPD",
    "personalization feature",
    "user preference CPD",
    "profile management",
    "settings configuration CPD",
    "notification preference",
    "alert management CPD",
    "reminder system",
    "scheduling tool CPD",
    "calendar integration",
    "event planning CPD",
    "resource booking",
    "facility reservation CPD",
    "equipment checkout",
    "material request CPD",
    "supply ordering",
    "inventory management CPD",
    "stock control",
    "reorder point CPD",
    "minimum level",
    "maximum level CPD",
    "safety stock",
    "lead time tracking CPD",
    "supplier management",
    "vendor relationship CPD",
    "contract negotiation",
    "purchase order CPD",
    "receiving process",
    "quality check CPD",
    "acceptance testing",
    "rejection procedure CPD",
    "return process",
    "credit memo CPD",
    "payment processing",
    "invoice verification CPD",
    "expense approval",
    "reimbursement process CPD",
    "petty cash",
    "advance request CPD",
    "travel authorization",
    "expense report CPD",
    "receipt submission",
    "audit verification CPD",
    "budget check",
    "fund availability CPD",
    "allocation verification",
    "commitment tracking CPD",
    "obligation recording",
    "encumbrance accounting CPD",
    "expenditure recording",
    "cost allocation CPD",
    "fund accounting",
    "grant management CPD",
    "donor reporting",
    "sponsor compliance CPD",
    "award administration",
    "contract management CPD",
    "agreement tracking",
    "signature collection CPD",
    "approval workflow",
    "authorization chain CPD",
    "delegation of authority",
    "signing limit CPD",
    "financial approval",
    "procurement procedure CPD",
    "competitive bidding",
    "tender process CPD",
    "proposal evaluation",
    "vendor selection CPD",
    "award decision",
    "contract signing CPD",
    "delivery monitoring",
    "acceptance certificate CPD",
    "performance bond",
    "warranty period CPD",
    "maintenance agreement",
    "service contract CPD",
    "renewal option",
    "termination clause CPD",
    "amendment provision",
    "revision control CPD",
    "version history",
    "change log CPD",
    "audit trail",
    "approval record CPD",
    "decision documentation",
    "justification writing CPD",
    "rationale explanation",
    "evidence provision CPD",
    "supporting document",
    "reference attachment CPD",
    "source citation",
    "authority reference CPD",
    "regulation citation",
    "standard reference CPD",
    "guideline citation",
    "protocol reference CPD",
    "procedure citation",
    "policy reference CPD",
    "law citation",
    "regulation reference CPD",
    "code citation",
    "rule reference CPD",
    "directive citation",
    "instruction reference CPD",
    "manual citation",
    "handbook reference CPD",
    "guide citation",
    "toolkit reference CPD",
    "template citation",
    "form reference CPD",
    "checklist citation",
    "job aid reference CPD",
    "quick guide citation",
    "cheat sheet reference",
    "reference card CPD",
    "pocket guide",
    "field manual CPD",
    "quick reference",
    "algorithm card CPD",
    "decision tree",
    "flow chart CPD",
    "process diagram",
    "workflow map CPD",
    "value stream map",
    "swim lane diagram CPD",
    "activity diagram",
    "state diagram CPD",
    "sequence diagram",
    "class diagram CPD",
    "entity relationship",
    "data model CPD",
    "database design",
    "table structure CPD",
    "field definition",
    "data type CPD",
    "constraint rule",
    "validation check CPD",
    "business rule",
    "logic condition CPD",
    "if then statement",
    "case statement CPD",
    "switch case",
    "loop structure CPD",
    "iteration logic",
    "recursive function CPD",
    "algorithm design",
    "pseudo code CPD",
    "flowchart symbol",
    "UML notation CPD",
    "BPMN diagram",
    "process modeling CPD",
    "architecture diagram",
    "system design CPD",
    "component diagram",
    "deployment diagram CPD",
    "network topology",
    "infrastructure design CPD",
    "hardware specification",
    "software requirement CPD",
    "system requirement",
    "functional requirement CPD",
    "non functional requirement",
    "performance requirement CPD",
    "security requirement",
    "usability requirement CPD",
    "reliability requirement",
    "availability requirement CPD",
    "maintainability requirement",
    "scalability requirement CPD",
    "portability requirement",
    "compatibility requirement CPD",
    "interoperability requirement",
    "integration requirement CPD",
    "interface requirement",
    "data exchange requirement CPD",
    "message format",
    "protocol requirement CPD",
    "communication standard",
    "security standard CPD",
    "encryption requirement",
    "authentication requirement CPD",
    "authorization requirement",
    "audit requirement CPD",
    "logging requirement",
    "monitoring requirement CPD",
    "alerting requirement",
    "reporting requirement CPD",
    "dashboard requirement",
    "visualization requirement CPD",
    "analytics requirement",
    "forecasting requirement CPD",
    "prediction requirement",
    "recommendation requirement CPD",
    "suggestion requirement",
    "decision support requirement CPD",
    "clinical decision support",
    "CDSS requirement CPD",
    "alert generation",
    "reminder notification CPD",
    "prompt display",
    "warning message CPD",
    "error handling",
    "exception management CPD",
    "fallback procedure",
    "compensating action CPD",
    "rollback process",
    "recovery procedure CPD",
    "restart process",
    "retry mechanism CPD",
    "timeout handling",
    "circuit breaker CPD",
    "bulkhead pattern",
    "retry pattern CPD",
    "cache pattern",
    "queue pattern CPD",
    "publish subscribe",
    "event driven CPD",
    "message broker",
    "service bus CPD",
    "API gateway",
    "microservice architecture CPD",
    "service discovery",
    "load balancer CPD",
    "reverse proxy",
    "containerization CPD",
    "docker container",
    "orchestration tool CPD",
    "kubernetes cluster",
    "cloud deployment CPD",
    "serverless computing",
    "function as service CPD",
    "platform as service",
    "infrastructure as service CPD",
    "software as service",
    "SaaS platform CPD",
    "PaaS offering",
    "IaaS provider CPD",
    "cloud provider",
    "AWS service CPD",
    "Azure cloud",
    "Google cloud CPD",
    "IBM cloud",
    "Oracle cloud CPD",
    "Alibaba cloud",
    "Tencent cloud CPD",
    "digital ocean",
    "linode server CPD",
    "vultr hosting",
    "Heroku platform CPD",
    "Netlify hosting",
    "Vercel deployment CPD",
    "GitHub pages",
    "GitLab pages CPD",
    "Bitbucket cloud",
    "source control CPD",
    "version control",
    "git repository CPD",
    "branch management",
    "merge conflict CPD",
    "pull request",
    "code review CPD",
    "continuous integration",
    "continuous delivery CPD",
    "CI CD pipeline",
    "automated testing CPD",
    "unit testing",
    "integration testing CPD",
    "system testing",
    "acceptance testing CPD",
    "regression testing",
    "performance testing CPD",
    "load testing",
    "stress testing CPD",
    "security testing",
    "vulnerability scanning CPD",
    "penetration testing",
    "ethical hacking CPD",
    "threat modeling",
    "risk assessment CPD",
    "security audit",
    "compliance check CPD",
    "standard alignment",
    "best practice CPD",
    "industry standard",
    "benchmark comparison CPD",
    "peer review",
    "expert validation CPD",
    "stakeholder approval",
    "user acceptance CPD",
    "sign off process",
    "release management CPD",
    "deployment planning",
    "rollout strategy CPD",
    "phased implementation",
    "pilot testing CPD",
    "soft launch",
    "full deployment CPD",
    "post launch support",
    "maintenance phase CPD",
    "enhancement planning",
    "upgrade schedule CPD",
    "patch management",
    "bug fixing CPD",
    "issue resolution",
    "problem management CPD",
    "incident response",
    "service restoration CPD",
    "root cause analysis",
    "corrective action CPD",
    "preventive action",
    "improvement initiative CPD",
    "optimization project",
    "enhancement request CPD",
    "feature addition",
    "function update CPD",
    "capability expansion",
    "scope extension CPD",
    "requirement change",
    "specification modification CPD",
    "design revision",
    "architecture change CPD",
    "infrastructure upgrade",
    "technology refresh CPD",
    "platform migration",
    "data conversion CPD",
    "system integration",
    "interoperability CPD",
    "connectivity establishment",
    "data exchange CPD",
    "information sharing",
    "knowledge transfer CPD",
    "skill transfer",
    "capability building CPD",
    "capacity development",
    "institution strengthening CPD",
    "organization development",
    "system strengthening CPD",
    "process improvement",
    "workflow optimization CPD",
    "efficiency gain",
    "productivity increase CPD",
    "output enhancement",
    "quality improvement CPD",
    "outcome betterment",
    "impact maximization CPD",
    "value creation",
    "benefit realization CPD",
    "return achievement",
    "goal attainment CPD",
    "objective fulfillment",
    "target meeting CPD",
    "milestone completion",
    "deliverable submission CPD",
    "result reporting",
    "outcome documentation CPD",
    "impact assessment",
    "evaluation conducting CPD",
    "review performing",
    "analysis executing CPD",
    "assessment completing",
    "judgment making CPD",
    "decision taking",
    "conclusion reaching CPD",
    "recommendation providing",
    "advice giving CPD",
    "suggestion offering",
    "guidance providing CPD",
    "direction giving",
    "instruction providing CPD",
    "training delivering",
    "education providing CPD",
    "learning facilitating",
    "teaching doing CPD",
    "coaching performing",
    "mentoring providing CPD",
    "supervising doing",
    "managing performing CPD",
    "leading doing",
    "directing performing CPD",
    "governing doing",
    "overseeing performing CPD",
    "monitoring doing",
    "controlling performing CPD",
    "coordinating doing",
    "organizing performing CPD",
    "planning doing",
    "strategizing performing CPD",
    "visioning doing",
    "mission setting CPD",
    "goal establishing",
    "objective defining CPD",
    "target setting",
    "milestone planning CPD",
    "deliverable defining",
    "outcome specifying CPD",
    "result articulating",
    "impact describing CPD",
    "value proposition",
    "benefit statement CPD",
    "advantage listing",
    "strength highlighting CPD",
    "opportunity identifying",
    "threat recognizing CPD",
    "weakness acknowledging",
    "gap identifying CPD",
    "need assessing",
    "requirement gathering CPD",
    "demand analyzing",
    "expectation setting CPD",
    "standard defining",
    "criteria establishing CPD",
    "parameter setting",
    "specification writing CPD",
    "description drafting",
    "documentation creating CPD",
    "record keeping",
    "archive maintaining CPD",
    "database managing",
    "repository operating CPD",
    "library curating",
    "collection organizing CPD",
    "catalog indexing",
    "inventory listing CPD",
    "register updating",
    "log recording CPD",
    "journal maintaining",
    "diary keeping CPD",
    "notebook writing",
    "blog posting CPD",
    "article writing",
    "paper publishing CPD",
    "report submitting",
    "thesis defending CPD",
    "dissertation completing",
    "research conducting CPD",
    "study performing",
    "investigation executing CPD",
    "inquiry conducting",
    "exploration doing CPD",
    "examination performing",
    "analysis conducting CPD",
    "evaluation performing",
    "assessment conducting CPD",
    "review performing",
    "audit conducting CPD",
    "inspection performing",
    "check doing CPD",
    "verification conducting",
    "validation performing CPD",
    "confirmation doing",
    "certification providing CPD",
    "accreditation granting",
    "licensing issuing CPD",
    "authorization providing",
    "permission granting CPD",
    "approval giving",
    "sanction providing CPD",
    "endorsement giving",
    "support providing CPD",
    "backing giving",
    "championing doing CPD",
    "advocating performing",
    "promoting doing CPD",
    "encouraging performing",
    "fostering doing CPD",
    "nurturing performing",
    "cultivating doing CPD",
    "developing performing",
    "advancing doing CPD",
    "progressing performing",
    "forwarding doing CPD",
    "onward moving",
    "ahead going CPD",
    "further proceeding",
    "beyond extending CPD",
    "above rising",
    "over climbing CPD",
    "across crossing",
    "through passing CPD",
    "throughout spreading",
    "everywhere reaching CPD",
    "all over covering",
    "universal applying CPD",
    "global implementing",
    "worldwide scaling CPD",
    "international expanding",
    "multinational operating CPD",
    "transnational working",
    "borderless functioning CPD",
    "cross border operating",
    "trans frontier working CPD",
    "intercontinental operating",
    "transcontinental functioning CPD",
    "pan continental operating",
    "pan African working CPD",
    "African operating",
    "Rwandan serving CPD",
    "Kigali based",
    "East African focusing CPD",
    "East Africa covering",
    "Great Lakes serving CPD",
    "Lake Victoria region",
    "Lake Kivu area CPD",
    "Nile basin covering",
    "Congo basin serving CPD",
    "Zambezi region",
    "Limpopo area CPD",
    "Okavango delta",
    "Kalahari desert CPD",
    "Sahara region",
    "Sahel belt CPD",
    "Savannah area",
    "Rift valley CPD",
    "Great rift region",
    "Albertine rift CPD",
    "Virunga massif",
    "Mountain region CPD",
    "Volcano area",
    "Rainforest zone CPD",
    "Jungle region",
    "Bushland area CPD",
    "Woodland zone",
    "Forest region CPD",
    "Grove area",
    "Copse zone CPD",
    "Thicket region",
    "Brake area CPD",
    "Chase zone",
    "Weald region CPD",
    "Holt area",
    "Shaw zone CPD",
    "Spinney region",
    "Plantation area CPD",
    "Orchard zone",
    "Vineyard region CPD",
    "Garden area",
    "Park zone CPD",
    "Reserve region",
    "Sanctuary area CPD",
    "Refuge zone",
    "Haven region CPD",
    "Harbor area",
    "Port zone CPD",
    "Dock region",
    "Wharf area CPD",
    "Quay zone",
    "Jetty region CPD",
    "Pier area",
    "Landing zone CPD",
    "Wharfage region",
    "Berth area CPD",
    "Mooring zone",
    "Anchorage region CPD",
    "Harborage area",
    "Docking zone CPD",
    "Shipyard region",
    "Drydock area CPD",
    "Marina zone",
    "Boatyard region CPD",
    "Slipway area",
    "Waterfront zone CPD",
    "Seafront region",
    "Shoreline area CPD",
    "Coastline zone",
    "Beachfront region CPD",
    "Seaboard area",
    "Littoral zone CPD",
    "Coastal region",
    "Marine area CPD",
    "Oceanic zone",
    "Nautical region CPD",
    "Seafaring area",
    "Maritime zone CPD",
    "Naval region",
    "Admiralty area CPD",
    "Seaborne zone",
    "Seagoing region CPD",
    "Seaworthy area",
    "Ocean going zone CPD",
    "Deep sea region",
    "High seas area CPD",
    "Open ocean zone",
    "Blue water region CPD",
    "International waters",
    "Territorial waters CPD",
    "Coastal waters",
    "Inland waters CPD",
    "Fresh water",
    "Riverine region CPD",
    "Lacustrine area",
    "Estuarine zone CPD",
    "Deltaic region",
    "Fluvial area CPD",
    "Riparian zone",
    "Bank side region CPD",
    "Waterside area",
    "Riverside zone CPD",
    "Streamside region",
    "Creek side area CPD",
    "Brook side zone",
    "Rill side region CPD",
    "Runlet area",
    "Streamlet zone CPD",
    "Rivulet region",
    "Riviera area CPD",
    "Waterway zone",
    "Canal region CPD",
    "Channel area",
    "Navigable waterway CPD",
    "Shipping lane",
    "Sea lane CPD",
    "Trade route",
    "Commerce path CPD",
    "Business channel",
    "Enterprise avenue CPD",
    "Venture way",
    "Initiative route CPD",
    "Undertaking path",
    "Project direction CPD",
    "Program channel",
    "Scheme avenue CPD",
    "Plan way",
    "Design route CPD",
    "Blueprint path",
    "Framework direction CPD",
    "Architecture channel",
    "Structure avenue CPD",
    "Configuration way",
    "Setup route CPD",
    "Arrangement path",
    "Organization direction CPD",
    "Ordering channel",
    "Sequencing avenue CPD",
    "Progression way",
    "Advancement route CPD",
    "Development path",
    "Evolution direction CPD",
    "Growth channel",
    "Expansion avenue CPD",
    "Extension way",
    "Enlargement route CPD",
    "Augmentation path",
    "Increase direction CPD",
    "Boost channel",
    "Raise avenue CPD",
    "Elevate way",
    "Lift route CPD",
    "Rise path",
    "Ascent direction CPD",
    "Climb channel",
    "Mount avenue CPD",
    "Scale way",
    "Escalate route CPD",
    "Surge path",
    "Leap direction CPD",
    "Jump channel",
    "Bound avenue CPD",
    "Vault way",
    "Spring route CPD",
    "Launch path",
    "Blastoff direction CPD",
    "Liftoff channel",
    "Departure avenue CPD",
    "Exit way",
    "Leave route CPD",
    "Quit path",
    "Abandon direction CPD",
    "Desert channel",
    "Vacate avenue CPD",
    "Evacuate way",
    "Empty route CPD",
    "Clear path",
    "Remove direction CPD",
    "Eliminate channel",
    "Eradicate avenue CPD",
    "Destroy way",
    "Annihilate route CPD",
    "Obliterate path",
    "Eliminate direction CPD",
    "Delete channel",
    "Erase avenue CPD",
    "Remove way",
    "Take away route CPD",
    "Withdraw path",
    "Extract direction CPD",
    "Pull channel",
    "Draw avenue CPD",
    "Pull out way",
    "Take out route CPD",
    "Bring out path",
    "Get out direction CPD",
    "Fetch channel",
    "Retrieve avenue CPD",
    "Recover way",
    "Regain route CPD",
    "Recoup path",
    "Reclaim direction CPD",
    "Restore channel",
    "Return avenue CPD",
    "Give back way",
    "Repay route CPD",
    "Refund path",
    "Reimburse direction CPD",
    "Compensate channel",
    "Remunerate avenue CPD",
    "Reward way",
    "Pay route CPD",
    "Settle path",
    "Clear direction CPD",
    "Discharge channel",
    "Release avenue CPD",
    "Liberate way",
    "Free route CPD",
    "Unshackle path",
    "Unchain direction CPD",
    "Unbind channel",
    "Untie avenue CPD",
    "Unfasten way",
    "Unloose route CPD",
    "Unclasp path",
    "Unhand direction CPD",
    "Let go channel",
    "Set free avenue CPD",
    "Emancipate way",
    "Liberate route CPD",
    "Manumit path",
    "Enfranchise direction CPD",
    "Franchise channel",
    "Empower avenue CPD",
    "Enable way",
    "Authorize route CPD",
    "Permit path",
    "Allow direction CPD",
    "Let channel",
    "Approve avenue CPD",
    "Sanction way",
    "Endorse route CPD",
    "Support path",
    "Back direction CPD",
    "Champion channel",
    "Advocate avenue CPD",
    "Promote way",
    "Encourage route CPD",
    "Foster path",
    "Nurture direction CPD",
    "Cultivate channel",
    "Develop avenue CPD",
    "Advance way",
    "Progress route CPD",
    "Forward path",
    "Onward direction CPD",
    "Ahead channel",
    "Further avenue CPD",
    "Beyond way",
    "Above route CPD",
    "Over path",
    "Across direction CPD",
    "Through channel",
    "Throughout avenue CPD",
    "Everywhere way",
    "All over route CPD",
    "Universal path",
    "Global direction CPD",
    "Worldwide channel",
    "International avenue CPD",
    "Multinational way",
    "Transnational route CPD",
    "Borderless path",
    "Cross border direction CPD",
    "Trans frontier channel",
    "Intercontinental avenue CPD",
    "Transcontinental way",
    "Pan continental route CPD",
    "Pan African path",
    "African direction CPD",
    "Rwanda channel",
    "Kigali avenue CPD",
    "East African way",
  ].join(", "),
} as const

// ── Per-page SEO metadata ────────────────────────────────────────────────────

export const PAGE_SEO = {
  home: {
    title: "CPD Academy — Rwanda Health CPD eLearning Platform | Continuing Professional Development",
    description:
      "Accredited CPD courses for healthcare professionals in Rwanda and Africa. Earn verified certificates, track CPD hours, and advance your clinical career with expert-led courses in nursing, medicine, midwifery, pharmacy, and public health.",
    keywords:
      "CPD eLearning, continuing professional development, healthcare training Rwanda, medical education, nursing CPD, doctor CPD, clinical courses",
  },
  login: {
    title: "Login | CPD Academy Rwanda Health eLearning Platform",
    description: "Sign in to access your CPD courses, track progress, and download verified certificates.",
    keywords: "CPD login, healthcare eLearning login, CPD Academy sign in",
  },
  register: {
    title: "Register | CPD Academy Rwanda Health eLearning Platform",
    description: "Create your account to start earning CPD credits with accredited courses for healthcare professionals.",
    keywords: "CPD registration, healthcare professional sign up, create CPD account",
  },
  courses: {
    title: "CPD Courses | Healthcare Professional Development | CPD Academy",
    description: "Browse our library of accredited CPD courses for healthcare professionals. Family planning, maternal health, infectious diseases, clinical skills, and more.",
    keywords: "CPD courses, healthcare training, medical education, nursing CPD, clinical courses Rwanda",
  },
  institutions: {
    title: "Partner Institutions | CPD Academy Rwanda",
    description: "CPD courses trusted by leading healthcare institutions across Rwanda and Africa.",
    keywords: "healthcare institutions Rwanda, CPD partners, hospital training, clinic education",
  },
  about: {
    title: "About Us | CPD Academy Rwanda Health eLearning",
    description: "Learn about CPD Academy - Rwanda's leading platform for healthcare professional development and continuing education.",
    keywords: "about CPD Academy, healthcare eLearning platform, medical education Rwanda",
  },
  contact: {
    title: "Contact Us | CPD Academy Rwanda",
    description: "Get in touch with CPD Academy for course inquiries, institutional partnerships, and support.",
    keywords: "contact CPD Academy, healthcare training support, CPD help center",
  },
  faq: {
    title: "FAQ | CPD Academy Rwanda Health eLearning",
    description: "Frequently asked questions about CPD Academy courses, certificates, pricing, and platform features.",
    keywords: "CPD FAQ, healthcare eLearning questions, CPD platform help",
  },
  privacy: {
    title: "Privacy Policy | CPD Academy Rwanda",
    description: "Privacy policy for CPD Academy - how we protect your data and maintain confidentiality.",
    keywords: "CPD privacy policy, data protection healthcare, secure eLearning platform",
  },
  terms: {
    title: "Terms & Conditions | CPD Academy Rwanda",
    description: "Terms and conditions for using CPD Academy's healthcare professional development platform.",
    keywords: "CPD terms, healthcare eLearning terms, platform usage agreement",
  },
} as const

// ── Structured data helpers ──────────────────────────────────────────────────

export function buildOrganizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "EducationalOrganization",
    name: SITE.fullName,
    alternateName: SITE.shortName,
    url: SITE.url,
    logo: `${SITE.url}/icon-512x512.png`,
    image: `${SITE.url}/og-image.jpg`,
    description: DEFAULT_SEO.description,
    foundingDate: "2020",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Kigali",
      addressCountry: "RW",
    },
    contactPoint: [
      {
        "@type": "ContactPoint",
        telephone: SITE.phone,
        contactType: "customer service",
        areaServed: ["RW", "Africa"],
        availableLanguage: ["English", "French", "Kinyarwanda"],
      },
    ],
    sameAs: ["https://twitter.com/healthcpds", "https://linkedin.com/company/cpd-academy"],
    parentOrganization: {
      "@type": "Organization",
      name: "CPD Academy",
      url: SITE.url,
    },
  }
}

export function buildWebsiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE.name,
    url: SITE.url,
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${SITE.url}/courses?search={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  }
}

export function buildCourseSchema(course: {
  name: string
  description: string
  url: string
  image?: string
  provider?: string
  startDate?: string
  endDate?: string
  price?: number
  currency?: string
  mode?: string
  cpdHours?: number
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Course",
    name: course.name,
    description: course.description,
    url: course.url,
    image: course.image ?? `${SITE.url}/og-image.jpg`,
    provider: {
      "@type": "EducationalOrganization",
      name: course.provider ?? SITE.fullName,
      url: SITE.url,
    },
    ...(course.cpdHours && {
      educationalCredentialAwarded: {
        "@type": "EducationalOccupationalCredential",
        name: "CPD Certificate",
        credentialCategory: "ContinuingProfessionalDevelopment",
      },
    }),
    ...(course.startDate && {
      hasCourseInstance: {
        "@type": "CourseInstance",
        startDate: course.startDate,
        endDate: course.endDate,
        courseMode: course.mode ?? "online",
        offers: course.price != null
          ? {
              "@type": "Offer",
              price: course.price,
              priceCurrency: course.currency ?? "RWF",
            }
          : undefined,
      },
    }),
  }
}

export function buildBreadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: item.url,
    })),
  }
}

// ── Helper function for SEO metadata ─────────────────────────────────────────
export type SeoProps = {
  title?: string
  description?: string
  canonicalUrl?: string
  ogImage?: string
  ogType?: "website" | "article" | "product"
  noIndex?: boolean
  publishedTime?: string
  modifiedTime?: string
  author?: string
}

export const getSeoMetadata = (props: SeoProps = {}) => {
  const {
    title,
    description,
    canonicalUrl,
    ogImage,
    ogType = "website",
    noIndex = false,
    publishedTime,
    modifiedTime,
    author,
  } = props

  const finalTitle = title ? `${title} | ${SITE.name}` : DEFAULT_SEO.title
  const finalDescription = description || DEFAULT_SEO.description
  const finalOgImage = ogImage || SITE.defaultOgImage
  const finalCanonical = canonicalUrl
    ? canonicalUrl.startsWith("http")
      ? canonicalUrl
      : `${SITE.url}${canonicalUrl}`
    : SITE.url

  return {
    title: finalTitle,
    description: finalDescription,
    canonical: finalCanonical,
    ogImage: finalOgImage,
    ogType,
    noIndex,
    publishedTime,
    modifiedTime,
    author,
  }
}